CompanyManager/CompanyManager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('employees/', include('employees.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('overview/', include('overview.urls')),
    path('assignments/', include('assignments.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CompanyManager/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog' #Best practice to call any view more precisely. 

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.detail, name = 'detail'),
]

CompanyManager/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.employees, name='employees'),
    path('add/', views.addEmployee, name='addEmployee'),
    path('showSuccessAdd/', views.showSuccessAdd, name='showSuccessAdd'),
    path('employee/<int:employees_pk>', views.viewEmployee, name='viewEmployee'),
    path('employee/<int:employees_pk>/edit_employee', views.editEmployee, name='editEmployee'),
    path('employee/<int:employees_pk>/deleted', views.deleteEmployee, name='deleteEmployee'),
    path('employee/<int:employees_pk>/emergency_contact',
         views.viewEmergencyContact, name='viewEmergencyContact'),
]

CompanyManager/CompanyManager/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'company_manager/index.html')

CompanyManager/CompanyManager/templates/company_manager/index.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Welcome</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
  		<a class="navbar-brand" href="#">Company</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  		</button>
		  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		    <div class="navbar-nav">
		      <a class="nav-link" href="{% url 'about' %}">About</a>
		      <a class="nav-link" href="{% url 'employees:employees' %}">Employees</a> 
		      <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
		    </div>
		  </div>
		</nav><br>
		
		<h1>Inside index.html!</h1>

		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	</body>
</html>