CompanyManager/CompanyManager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('employees/', include('employees.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('overview/', include('overview.urls')),
    path('assignments/', include('assignments.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CompanyManager/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog' #Best practice to call any view more precisely. 

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.detail, name = 'detail'),
]

CompanyManager/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.employees, name='employees'),
    path('add/', views.addEmployee, name='addEmployee'),
    path('showSuccessAdd/', views.showSuccessAdd, name='showSuccessAdd'),
    path('employee/<int:employees_pk>', views.viewEmployee, name='viewEmployee'),
    path('employee/<int:employees_pk>/edit_employee', views.editEmployee, name='editEmployee'),
    path('employee/<int:employees_pk>/deleted', views.deleteEmployee, name='deleteEmployee'),
    path('employee/<int:employees_pk>/emergency_contact',
         views.viewEmergencyContact, name='viewEmergencyContact'),
]

CompanyManager/employees/models.py
from django.db import models
from django.contrib.auth.models import User

# Employee types list for the employeeType choice field.
EMP_TYPES = {
    ("potential", "Potential"),
    ("hourly", "Hourly"),
    ("salaried", "Salaried"),
    ("manager", "Manager"),
    ("executive", "Executive"),
}

STATUS_TYPES = {
    ("active", "Active"),
    ("hiatus", "Hiatus"),
    ("former", "Former"),
}

SKILL_RANKS = {
    ("novice", "Novice"),
    ("intermediate", "Intermediate"),
    ("advanced", "Advanced"),
    ("expert", "Expert"),
}

class Employee(models.Model):
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    position = models.CharField(max_length=200, blank=True)
    birthDate = models.DateField(blank=True)
    dateCreated = models.DateTimeField(auto_now_add=True, null=True) # Required so no blank=True
    dateHired = models.DateTimeField(null=True, blank=True)
    dateFired = models.DateTimeField(null=True, blank=True)
    wage = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    emergencyContact = models.CharField(max_length=400, blank=True)
    #TODO phone = models.
    employeeType = models.CharField(
        max_length=20,
        choices=EMP_TYPES,
        default='potential',
        )
    address = models.CharField(max_length=1000)
    email = models.EmailField(blank=True)
    picture = models.ImageField(upload_to='employees/images/',
                                default='employees/images/240x240_default_img.jpg',
                                blank=True)
    cur_assignment = models.TextField(blank=True)
    recorded_by = models.ForeignKey(User, default=None, null=True, on_delete=models.CASCADE)
    # So the actual name of the object appears when looking at the database in Django Admin for example
    def __str__(self):
        return self.lastName + ", " + self.firstName

class Experience(models.Model):
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        null=True,
        )
    from_date = models.DateField(null=True)
    to_date = models.DateField(null=True)
    text = models.TextField(default="INSIDE EXPERIENCE TEXT", blank=True)

class Skill(models.Model):
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        null=True,
        )
    name = models.CharField(max_length=200, blank=True)
    rank = models.CharField(
        max_length=50,
        choices=SKILL_RANKS,
        default='novice',
        )

class Assignment(models.Model):
    employee = models.ForeignKey(
        Employee,
        on_delete=models.CASCADE,
        null=True,
        )
    title = models.CharField(max_length=300, blank=True)
    description = models.TextField(default="ASSIGNMENT DESCRIPTION", blank=True)

CompanyManager/employees/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import modelformset_factory
from .models import Employee
from .models import Experience
from .models import Skill
from .models import Assignment

class EmployeeForm(ModelForm):
    class Meta:
        #TODO add way to select an image! 
        model = Employee
        fields = ['firstName',
                  'lastName',
                  'position',
                  'birthDate',
                  'dateHired',
                  'dateFired',
                  'wage',
                  'emergencyContact',
                  'employeeType',
                  'address',
                  'email',
                  'picture',
                  'cur_assignment']
        widgets = {
            'birthDate': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'dateHired': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'dateFired': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['birthDate'].required = False
        self.fields['dateHired'].required = False
        self.fields['dateFired'].required = False
        self.fields['picture'].required = False
        self.fields['cur_assignment'].required = False

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ['name',
                  'rank',]

class ExperienceForm(ModelForm):
    class Meta:
        model = Experience
        fields = ['from_date',
                  'to_date',
                  'text',]
        # Using widgets to specify date type in the form fixed issue where it
        # only showed up as a text field.
        widgets = {
            'from_date':forms.DateInput(attrs={'type':'date'}),
            'to_date':forms.DateInput(attrs={'type':'date'}),
                }

class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['title',
                  'description',]

CompanyManager/employees/views.py
from django.contrib import messages
from django.db import IntegrityError, transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import modelformset_factory
from .models import Employee
from .forms import EmployeeForm
from .models import Experience
from .forms import ExperienceForm
from .models import Skill
from .forms import SkillForm
from .models import Assignment
from .forms import AssignmentForm
from django.forms.formsets import formset_factory
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

@login_required
def employees(request):
    emps = Employee.objects.all()
    return render(request, 'employees/employees.html', {'emps': emps})

@login_required
def addEmployee(request):
    ExpFormSet = formset_factory(ExperienceForm, extra=1)
    SkillFormSet = formset_factory(SkillForm, extra=1)
    if request.method == 'GET':
        employee_form = EmployeeForm()
        exp_formset = ExpFormSet()
        skill_formset = SkillFormSet()
        context = {'employee_form':employee_form,
                   'exp_formset':exp_formset,
                   'skill_formset':skill_formset}
        return render(request, 'employees/addemployee.html', context)

    if request.method == 'POST':
        # Essentially takes the form from GET and melds the fields into a POST thing. Awesome.
        try:
            employee_form = EmployeeForm(request.POST)
            exp_formset_post = ExpFormSet(request.POST)
            skill_formset_post = SkillFormSet(request.POST)

            if employee_form.is_valid() and exp_formset_post.is_valid() and skill_formset_post.is_valid():
                #employee = employee_form.save(commit = False)
                #employee.recorded_by(request.user)
                emp = employee_form.save()

                saveExperience(exp_formset_post, emp, request)
                saveSkill(skill_formset_post, emp, request)

            # Redirect is the action in the form in the addemployee template.
            context = {'employee_form': employee_form, 'exp_formset': exp_formset_post}
            return render(request, 'employees/addemployeesuccess.html', context)
        except ValueError:
            return render(request, 'employees/addemployee.html',
                          {'employee_form': EmployeeForm(),
                           'error':'Bad data passed in. Try again.'})

#Helper function for addEmployee
def saveExperience(exp_formset_post, emp, request):
    new_exp = [] #Save the data for each form in the formset.

    for exp in exp_formset_post:
        from_date = exp.cleaned_data.get('from_date')
        to_date = exp.cleaned_data.get('to_date')
        text = exp.cleaned_data.get('text')

        if from_date and to_date and text:
            new_exp.append(Experience(from_date=from_date,
                                      to_date=to_date, text=text,
                                      employee=emp))

    saveFormset(new_exp, request, Experience)

# Helper function for addEmployee
def saveSkill(skill_formset_post, emp, request):
    new_skill = [] # Save the data for each form in the formset

    for skill in skill_formset_post:
        name = skill.cleaned_data.get('name')
        rank = skill.cleaned_data.get('rank')

        if name and rank:
            new_skill.append(Skill(name=name, rank=rank, employee=emp))

    saveFormset(new_skill, request, Skill)

# Helper function for addEmployee
def saveAssignment(assignment_formset_post, emp, request):
    new_assignment = [] # Save the data for each form in the formset

    for assignment in assignment_formset_post:
        title = assignment.cleaned_data.get('title')
        description = assignment.cleaned_data.get('description')

        if title and description:
            new_assignment.append(Assignment(title=title, description=description, employee=emp))

    saveFormset(new_assignment, request, Assignment)

# Helper function for the saveExperience and saveSkill functions.
def saveFormset(form_list, request, model):

    try:
        with transaction.atomic():
            #Replace old entries with the new ones
            #Experience.objects.filter(user=user).delete()
            model.objects.bulk_create(form_list)

            #Notify users that it worked
            messages.success(request, 'Experience has been updated.')
    except IntegrityError: #transaction failed
        messages.error(request, 'There was an error updating experience.')
        return redirect('employees:employees')

@login_required
def showSuccessAdd(request):
    return render(request, 'employees/addemployeesuccess.html')

@login_required
def viewEmployee(request, employees_pk):
    emp = get_object_or_404(Employee, pk=employees_pk)
    exp_list = emp.experience_set.all()
    skill_list = emp.skill_set.all()
    if request.method == 'GET':
        emp_form = EmployeeForm(instance=emp)
        return render(request, 'employees/employeedetail.html',
                      {'emp':emp, 'exp_list':exp_list, 'skill_list':skill_list})

    try:
        emp_form = EmployeeForm(request.POST, instance=emp)
        emp_form.save()
        return redirect('employees:employees')
    except ValueError:
        return render(request, 'employees/addemployee.html',
                      {'form': EmployeeForm(), 'error':'Bad data passed in. Try again.'})

@login_required
#DON'T USE THIS VIEW. MAKE IT SO INDIVIDUAL ELEMENTS LIKE IMAGE OR PERSONAL SECTIONS ARE DIRECTLY LINKED
def editEmployee(request, employees_pk):
    emp = get_object_or_404(Employee, pk=employees_pk)
    if request.method == 'GET':
        form = EmployeeForm(instance=emp)
        return render(request,
                      'employees/edit_sections/editemployeebase.html',
                      {'emp':emp, 'form':form})
    try:
        form = EmployeeForm(request.POST, instance=emp)
        form.save()
        return redirect('employees:employees')
    except ValueError:
        return render(request, 'employees/addemployee.html',
                      {'form': EmployeeForm(),
                       'error':'Bad data passed in. Try again.'})

@login_required
def deleteEmployee(request, employees_pk):
    emp = get_object_or_404(Employee, pk=employees_pk)
    if request.method == 'POST':
        emp.delete()
        return redirect('employees:employees')

@login_required
def viewEmergencyContact(request, employees_pk):
    emp = get_object_or_404(Employee, pk=employees_pk)
    return render(request, 'employees/emp_emergency_contact.html', {'emp':emp})

CompanyManager/employees/templates/employees/addemployee.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Add Employee</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	<body>
		{% block content %}

        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}

        <!-- TODO add way to select an image! -->
        <div class="container">
        <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <h1>Add Employee</h1> 
            <br><br>
            <h2>{{ error }}</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Personal</h3><br>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.firstName | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.lastName | as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.birthDate | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.email | as_crispy_field }}
                    </div>
                </div>
                {{ employee_form.address | as_crispy_field }}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.employeeType | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.position | as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                    {{ employee_form.dateHired | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.dateFired | as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ employee_form.wage | as_crispy_field }}
                    </div>
                </div>
                <br>

                <h3>Skills</h3><br> 

                {{ skill_formset.management_form }}

                <div class="skill-formset">
                    {% for skill_form in skill_formset %}
                        {{ skill_form.name | as_crispy_field }}
                        {% if skill_formset.text.errors %}
                            {% for error in skill_formset.text.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}   
                            
                        <br>

                        {{ skill_form.rank | as_crispy_field }}
                        {% if skill_formset.text.errors %}
                            {% for error in skill_formset.text.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}   
                    {% endfor %}
                </div>

                <h3>Experience</h3><br>

                {{ exp_formset.management_form }}

                <div class="exp-formset">
                    {% for exp_form in exp_formset %}
                        {{ exp_form.from_date | as_crispy_field }}
                        {% if exp_formset.from_date.errors %}
                            {% for error in exp_formset.from_date.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                        
                        <br>

                        {{ exp_form.to_date | as_crispy_field }}
                        {% if exp_formset.to_date.errors %}
                            {% for error in exp_formset.to_date.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}

                        <br>

                        {{ exp_form.text | as_crispy_field }}
                        {% if exp_formset.text.errors %}
                            {% for error in exp_formset.text.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>

                {% if exp_formset.non_form_errors %}
                    {% for error in exp_formset.non_form_errors %} 
                        {{ error|escape }}
                    {% endfor %}
                {% endif %}

                <br><br>
                <button type="submit">Submit</button>
            </form>
        </div>
        <!-- Include formset plugin - including jQuery dependency -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        <script>
            $('.skill-formset').formset({
                addText: 'add skill',
                deleteText: 'remove'
            });
        </script>
        <script>
            $('.exp-formset').formset({
                addText: 'add experience',
                deleteText: 'remove'
            });
        </script>
		{% endblock %}
	</body>
</html>

CompanyManager/employees/templates/employees/addemployeesuccess.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Employee Confirmation</title>
    </head>
    <body>
        <h1>Adding employee successful!</h1>
        <p>Testing first name: {{ employee_form.firstName.value }}</p>
        <p>Testing last name: {{ employee_form.lastName.value }}</p>
        {% for exp_form in exp_formset %}
            <p>Testing formset from_date: {{ exp_form.from_date.value }}</p>
            <p>Testing formset to_date: {{ exp_form.to_date.value }}</p>
            <p>Testing formset text: {{ exp_form.text.value }}</p>
        {% endfor %}
        <a href="#">Edit this employee</a>
        <a href="{% url 'employees:employees' %}">Go to employees list</a>
    </body>
</html>

CompanyManager/employees/templates/employees/editemployeedetail.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Edit Employee Details</title>
        <link rel="stylesheet" href="{% static "css/edit_employee_base.css" %}"/> 
	</head>

	<body>
		{{ error }}

        <div id="wrapper" class="toggled">
            <!--Sidebar-->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="{{request.META.HTTP_REFERER}}">
                            < Back
                        </a>
                    </li>
                    <li>
                        <a href="#">Image</a>
                    </li>
                    <li>
                        <a href="#">Personal</a>
                    </li>
                    <li>
                        <a href="#">Experience</a>
                    </li> 
                    <li>
                        <a href="#">Skills</a>
                    </li>
                    <li>
                        <a href="#">Experience</a>
                    </li>
                </ul>
            </div>
            <!--End Sidebar-->

            <!--Page Content-->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <h1>Page Content</h1>
                </div>
            </div>
            <!--End Page Content-->

        </div>

	</body>
	{% block content %}{% endblock %}
</html>

CompanyManager/employees/templates/employees/editexperience.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
<html>
	{% load static %}
    <head>
        <meta charset="utf-8">
        <title>Edit Experience</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
    </head>

    <body>
		{% block content %}

		{% endblock %}
    </body>
</html>

CompanyManager/employees/templates/employees/emp_emergency_contact.html
<!DOCTYPE html> {% extends 'home/base.html' %} 
<html>
	{% load static %}
    <head>
        <meta charset="utf-8">
        <title>Employee Emergency Contact</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
    </head>

	{% block content %}
    <body>
        <h1>EMERGENCY CONTACT</h1>
    </body>
	{% endblock %}
</html>

CompanyManager/employees/templates/employees/employeedetail.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Employee Details</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	{% block content %}
	<body>
        <a href="{{request.META.HTTP_REFERER}}">Back</a>
        <!--<a href="{% url 'employees:editEmployee' emp.id %}">Edit</a>-->
        <div class="row h-100">
            <div class="col-md-4" align="center">
                <div class="card border-0">
                    <img class="card-img-top img-responsive" src="{{ emp.picture.url }}" alt="No image found.">
                    <div class="card-body">
                        <h1 class="card-title">{{ emp.firstName }} {{ emp.lastName }}</h1>
                        <h5 class="card-text">Position</h5>
                        <h5 class="card-text">Employee from xxxx to xxxx</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-12">
                        <button onclick="toggleEssentials()" id="essentials-toggle" class="col align-self-start">
                            Hide Essentials</button>
                        <div class="card">
                            <div id="emp-essentials" class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <p><h5>First Name:</h5> {{ emp.firstName }}</p>
                                        <p><h5>Birth Date:</h5> {{ emp.birthDate }}</p>
                                        <p><h5>Rate:</h5> </p>
                                        <p><h5>Phone:</h5> </p>
                                    </div>
                                    <div class="col-md-6">
                                        <p><h5>Last Name:</h5> {{ emp.lastName }}</p>
                                        <p><h5>Email:</h5> {{ emp.email }}</p>
                                        <p><h5>Address:</h5> {{ emp.address }}</p>
                                        <p><h5>Emergency Contact:</h5> TODO: MAKE THIS A LINK</p>
                                    </div>   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div id="employeeDetailCarousel" class="carousel slide w-100" data-interval="false" data-ride="carousel">

                                <!--Controls-->
                                <div class="controls-top">
                                    <div class="btn-group btn-group-toggle w-100" data-toggle="buttons">
                                        <label class="btn btn-secondary btn-lg active">
                                            <input type="radio" name="option_skill" autocomplete="off" href="#employeeDetailCarousel" data-slide-to="0" checked>Skills
                                        </label>
                                        <label class="btn btn-secondary btn-lg">
                                            <input type="radio" name="option_experience" autocomplete="off" href="#employeeDetailCarousel" data-slide-to="1">Experience
                                        </label>
                                        <label class="btn btn-secondary btn-lg">
                                            <input type="radio" name="option_assignments" autocomplete="off" href="#employeeDetailCarousel" data-slide-to="2">Assignments
                                        </label>
                                    </div>
                                </div>
                                <!--End Controls-->
                                
                                <!--Carousel Content-->
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <h1>Skills</h1>
                                        {% for skill in skill_list %}
                                        <ul>
                                            <li>{{ skill.name }}</li>
                                            <li>{{ skill.rank }}</li>
                                        </ul>
                                        {% endfor %}
                                    </div>
                                    <div class="carousel-item">
                                        <h1>Experience</h1>
                                        {% for exp in exp_list %}
                                        <ul>
                                            <li>{{ exp.from_date }}</li>
                                            <li>{{ exp.to_date }}</li>
                                            <li>{{ exp.text }}</li>
                                        </ul>
                                        {% endfor %}
                                    </div>
                                    <div class="carousel-item">
                                        <h1>Assignments</h1>
                                    </div>
                                </div>
                                <!--End Carousel Content-->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'js/employee_detail.js' %}"></script>
	</body>
	{% endblock %}
</html>

CompanyManager/employees/templates/employees/employees.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	<head>
	{% block content %}
	{% load static %}
		<meta charset="utf-8">
		<title>Employees</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	<body>
		
		<a href="{% url 'employees:addEmployee' %}">Add Employee</a>
		<table class="table table-hover table-borderless">
			<thead class="tablehead-custom">
				<tr>
                    <th scope="col">Date Hired</th>
					<th scope="col">Type</th>
					<th scope="col">Name</th>
					<th scope="col">Current Assignment</th>
                    <th scope="col">Edit</th>
				</tr>
			</thead>
			<tbody>

			{% for emp in emps  %}
				<tr scope="row"></th>
                <td>{{ emp.dateHired|date:"Y-M-d" }}</td>
				<td>{% if emp.employeeType == "executive" %}<b>{% endif %}
					{{ emp.employeeType }}
				{% if emp.employeeType == "executive" %}</b>{% endif %}</td>
				<td>{{ emp.lastName }}, {{ emp.firstName }}</td>
				<td>{{ emp.cur_assigment }}</td>
                <td><a class="btn btn-info btn-small tbl-custom-btn" href="{% url 'employees:viewEmployee' emp.id %}">Open</a>
			{% endfor %}
				
			</tbody>
		</table>
		
	</body>
	{% endblock %}
</html>

CompanyManager/employees/templates/employees/index.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Welcome</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
  		<a class="navbar-brand" href="#">Navbar</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  		</button>
		  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		    <div class="navbar-nav">
		      <a class="nav-link" href="{% url 'about' %}">About</a>
		      <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
		    </div>
		  </div>
		</nav><br>
		
		<h1>Inside index.html!</h1>

		<table class="table">
			<thead>
				<tr>
					<th scope="col">ID</th>
					<th scope="col">First Name</th>
					<th scope="col">Last Name</th>
				</tr>
			</thead>
			<tbody>
			{% for employee in employees  %}
				<tr scope="row"></th>
				<td>{{ employee.firstName }}</td>
				<td>{{ employee.lastName }}</td>
			{% endfor %}
				
			</tbody>
		</table>
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	</body>
</html>