CompanyManager/CompanyManager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('employees/', include('employees.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('overview/', include('overview.urls')),
    path('assignments/', include('assignments.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CompanyManager/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog' #Best practice to call any view more precisely. 

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.detail, name = 'detail'),
]

CompanyManager/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.employees, name='employees'),
    path('add/', views.addEmployee, name='addEmployee'),
    path('showSuccessAdd/', views.showSuccessAdd, name='showSuccessAdd'),
    path('employee/<int:employees_pk>', views.viewEmployee, name='viewEmployee'),
    path('employee/<int:employees_pk>/edit_employee', views.editEmployee, name='editEmployee'),
    path('employee/<int:employees_pk>/deleted', views.deleteEmployee, name='deleteEmployee'),
    path('employee/<int:employees_pk>/emergency_contact',
         views.viewEmergencyContact, name='viewEmergencyContact'),
]

CompanyManager/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
        path('', views.home, name='home'),
        path('signup/', views.signupuser, name='signupuser'),
        path('logout/', views.logoutuser, name='logoutuser'),
        path('login/', views.loginuser, name='loginuser'),
]

CompanyManager/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate

def home(request):
    if request.user.is_authenticated:
        return redirect('overview:overview')
    return render(request, 'home/home.html')

def signupuser(request):
    if request.method == "GET":
        return render(request, 'home/signupuser.html', {'form': UserCreationForm()})
    if request.POST['password1'] == request.POST['password2']:
        try:
            user = User.objects.create_user(request.POST['username'],
                                            password=request.POST['password2'])
            user.save()
            login(request, user)
            return redirect('employees:employees')
        except IntegrityError:
            return render(request, 'home/signupuser.html',
                          {'form': UserCreationForm(), 'error':'Usernames must be unique.'})
    else:
        return render(request, 'home/signupuser.html',
                      {'form': UserCreationForm(), 'error':'Passwords did not match'})

def loginuser(request):
    if request.method == "GET":
        return render(request, 'home/loginuser.html', {'form': AuthenticationForm()})
    user = authenticate(request,
                        username=request.POST['username'], 
                        password=request.POST['password'])
    if user is None:
        return render(request,
                      'home/loginuser.html',
                      {'form': AuthenticationForm(),
                             'error':'Username and/or password are not valid'})
    login(request, user)
    return redirect('employees:employees')
     
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
    return redirect('home:home')

CompanyManager/home/templates/home/base.html
<!--Basic template-->

<!DOCTYPE html>

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<link rel="icon" type="image/png" href="/media/base/images/CMLogo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
	</head>

	<body>
        <nav class="navbar navbar-expand-lg navbar-custom">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="/media/base/images/CMLogo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    Company
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

                {% if user.is_authenticated %}

                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'employees:employees' %}">Employees</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:all_blogs' %}">Log</a></li>
                        </ul>

                {% endif %}

                <ul class="navbar-nav ml-auto">

                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <h5>Logged in as {{ user.username }} &nbsp;</h5>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'home:logoutuser' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Logout</button>
                            </form>
                        </li>

                    {% else %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'home:signupuser' %}">Sign Up</a></li><br>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:loginuser' %}">Log In</a></li>

                    {% endif %}

                </ul>
            </div>
        </nav><br>

		{% block content %}{% endblock %}
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	</body>
</html>

CompanyManager/home/templates/home/home.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Company Manager</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	<body>
		{% block content %}
            <div class="container">
                <div class="jumbotron">
                  <h1 class="display-4">Welcome!</h1>
                  <p class="lead">New users sign up here.</p>
                  <p class="lead">
                  <a class="btn btn-primary btn-lg" href="{% url 'home:signupuser' %}" role="button">Sign up</a>
                  </p>
                  <hr class="my-4">
                  <p>Already a member? Log in here.</p>
                  <p class="lead">
                  <a class="btn btn-primary btn-lg" href="{% url 'home:loginuser' %}" role="button">Log in</a>
                  </p>
                </div>
            </div>
		{% endblock %}
	</body>
</html>

CompanyManager/home/templates/home/loginuser.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Login</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	<body>
		{% block content %}
		<h1>Login User</h1> 
		<h2>{{ error }}</h2>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Login</button>
		</form>
		{% endblock %}
	</body>
</html>

CompanyManager/home/templates/home/signupuser.html
<!DOCTYPE html>
{% extends 'home/base.html' %}

<html>
	{% load static %}
	<head>
		<meta charset="utf-8">
		<title>Sign Up</title>
		<link rel="stylesheet" href="{% static "css/default.css" %}"/>
	</head>

	<body>
		{% block content %}
		<h1>Add New User</h1> 
		<h2>{{ error }}</h2>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Sign Up</button>
		</form>
		{% endblock %}
	</body>
</html>